#!/bin/bash
exec >>/var/log/vpngui.log 2>&1

while :; do
	sleep 2
	/bin/bash /var/www/vpngui/scriptvpn.sh vpnsetup
#* * * * * bash /var/www/vpngui/scriptvpn.sh cleanreloadedvpn
#0,30 * * * * bash /var/www/vpngui/scriptvpn.sh allping-update	
done
