#! /bin/sh -e

### BEGIN INIT INFO
# Provides:          scriptvpnd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO


DAEMON="/var/www/vpngui/daemon/scriptvpnd" #ligne de commande du programme
DEAMON_OPT=""  #argument à utiliser par le programme
DAEMONUSER="root" #utilisateur du programme
DEAMON_NAME="scriptvpnd" #Nom du programme (doit être identique à l'exécutable)
PIDFILE=/var/run/$DEAMON_NAME.pid

PATH="/sbin:/bin:/usr/sbin:/usr/bin" #Ne pas toucher
time=`date +"%y-%m-%d at %X"`
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $DEAMON_NAME Daemon"
	start-stop-daemon --background --name $DEAMON_NAME --pidfile $PIDFILE --start --quiet --user $DAEMONUSER --exec $DAEMON -- $DEAMON_OPT 
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DEAMON_NAME Daemon"
        start-stop-daemon --name $DEAMON_NAME --stop --retry 5 --quiet --name $DEAMON_NAME
	log_end_msg $?
}

case "$1" in

        start|stop)
		echo "$1 system $DEAMON_NAME - $time" >> /var/log/vpngui.log
                d_${1}
                ;;

#        restart|reload|force-reload)
			
#			echo "t1"
#                        d_stop
#			echo "t2"
#		        d_start
		
#                ;;

        force-stop)
		echo "Force stoping system $DEAMON_NAME - $time" >> /var/log/vpngui.log
               d_stop
                killall -q $DEAMON_NAME || true
                sleep 2
                killall -q -9 $DEAMON_NAME || true
                ;;

        status)
                status_of_proc "$DEAMON_NAME" "$DAEMON" "system-wide $DEAMON_NAME" && exit 0 || exit $?
                ;;
        *)
#                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
		echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|status}"
                exit 1
                ;;
esac
exit 0
