<?
// www.phpbb_smilies
$phpbb_smilies = array(
  array('code'=>':D','emotion'=>'Très content','smiley_url'=>'icon_e_biggrin.gif'),
  array('code'=>':-D','emotion'=>'Très content','smiley_url'=>'icon_e_biggrin.gif'),
  array('code'=>':grin:','emotion'=>'Très content','smiley_url'=>'icon_e_biggrin.gif'),
  array('code'=>':)','emotion'=>'Sourire','smiley_url'=>'icon_e_smile.gif'),
  array('code'=>':-)','emotion'=>'Sourire','smiley_url'=>'icon_e_smile.gif'),
  array('code'=>':smile:','emotion'=>'Sourire','smiley_url'=>'icon_e_smile.gif'),
  array('code'=>';)','emotion'=>'Clin d’oeil','smiley_url'=>'icon_e_wink.gif'),
  array('code'=>';-)','emotion'=>'Clin d’oeil','smiley_url'=>'icon_e_wink.gif'),
  array('code'=>':wink:','emotion'=>'Clin d’oeil','smiley_url'=>'icon_e_wink.gif'),
  array('code'=>':(','emotion'=>'Triste','smiley_url'=>'icon_e_sad.gif'),
  array('code'=>':-(','emotion'=>'Triste','smiley_url'=>'icon_e_sad.gif'),
  array('code'=>':sad:','emotion'=>'Triste','smiley_url'=>'icon_e_sad.gif'),
  array('code'=>':o','emotion'=>'Surprise','smiley_url'=>'icon_e_surprised.gif'),
  array('code'=>':-o','emotion'=>'Surprise','smiley_url'=>'icon_e_surprised.gif'),
  array('code'=>':eek:','emotion'=>'Surprise','smiley_url'=>'icon_e_surprised.gif'),
  array('code'=>':shock:','emotion'=>'Choqué','smiley_url'=>'icon_eek.gif'),
  array('code'=>':?','emotion'=>'Confus','smiley_url'=>'icon_e_confused.gif'),
  array('code'=>':-?','emotion'=>'Confus','smiley_url'=>'icon_e_confused.gif'),
  array('code'=>':???:','emotion'=>'Confus','smiley_url'=>'icon_e_confused.gif'),
  array('code'=>'8-)','emotion'=>'Cool','smiley_url'=>'icon_cool.gif'),
  array('code'=>':cool:','emotion'=>'Cool','smiley_url'=>'icon_cool.gif'),
  array('code'=>':lol:','emotion'=>'Rire','smiley_url'=>'icon_lol.gif'),
  array('code'=>':x','emotion'=>'Fou','smiley_url'=>'icon_mad.gif'),
  array('code'=>':-x','emotion'=>'Fou','smiley_url'=>'icon_mad.gif'),
  array('code'=>':mad:','emotion'=>'Fou','smiley_url'=>'icon_mad.gif'),
  array('code'=>':P','emotion'=>'Tire la langue','smiley_url'=>'icon_razz.gif'),
  array('code'=>':-P','emotion'=>'Tire la langue','smiley_url'=>'icon_razz.gif'),
  array('code'=>':-p','emotion'=>'Tire la langue','smiley_url'=>'icon_razz.gif'),
  array('code'=>':p','emotion'=>'Tire la langue','smiley_url'=>'icon_razz.gif'),
  array('code'=>':razz:','emotion'=>'Tire la langue','smiley_url'=>'icon_razz.gif'),
  array('code'=>':oops:','emotion'=>'Embarrassé','smiley_url'=>'icon_redface.gif'),
  array('code'=>':cry:','emotion'=>'Très triste, en pleurs','smiley_url'=>'icon_cry.gif'),
  array('code'=>':evil:','emotion'=>'Diable','smiley_url'=>'icon_evil.gif'),
  array('code'=>':twisted:','emotion'=>'Diable rieur','smiley_url'=>'icon_twisted.gif'),
  array('code'=>':roll:','emotion'=>'Yeux tournants','smiley_url'=>'icon_rolleyes.gif'),
  array('code'=>':!:','emotion'=>'Exclamation','smiley_url'=>'icon_exclaim.gif'),
  array('code'=>':?:','emotion'=>'Question','smiley_url'=>'icon_question.gif'),
  array('code'=>':idea:','emotion'=>'Idée','smiley_url'=>'icon_idea.gif'),
  array('code'=>':arrow:','emotion'=>'Flèche','smiley_url'=>'icon_arrow.gif'),
  array('code'=>':|','emotion'=>'Neutre','smiley_url'=>'icon_neutral.gif'),
  array('code'=>':-|','emotion'=>'Neutre','smiley_url'=>'icon_neutral.gif'),
  array('code'=>':mrgreen:','emotion'=>'M. Vert','smiley_url'=>'icon_mrgreen.gif'),
  array('code'=>':geek:','emotion'=>'Geek','smiley_url'=>'icon_e_geek.gif'),
  array('code'=>':ugeek:','emotion'=>'Geek barbu','smiley_url'=>'icon_e_ugeek.gif')
);

?>